# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 529086899e3702217a45d7913faa8b95953efc1cee68be541c8e6090cd803b75d33b03187027b9cf3f3ee15cde9091ab501bade6035e212661183a0cc54221f6

test:
  secret_key_base: ecd87effe6e4a3f15cec1e62b657feabd822bc4a04977b64c382a82b303e209ab58d87b8cc10ab58260964cd62dd9032b3ca693c107a8abc6f677a646f766d59

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
